#!/usr/bin/env bash

tmux split-window -v -p 30
tmux split-window -h -p 50

tmux send-keys -t -1 "npm start" Enter
tmux send-keys "npm run server" Enter

# Consider sending `actvenv` on newly created windows,
# eg.
# tmux send-keys -t :1 actvenv Enter
# tmux send-keys -t :2.0 actvenv Enter
# tmux send-keys -t :2.1 \
